CREATE DATABASE IF NOT EXISTS hti_iz;
CREATE DATABASE IF NOT EXISTS hti_iz_account;
CREATE USER IF NOT EXISTS 'hti'@'%' IDENTIFIED BY 'db_password';
GRANT ALL PRIVILEGES ON hti_iz.* TO 'hti'@'%' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON hti_iz_account.* TO 'hti'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;