CREATE DATABASE IF NOT EXISTS hit_himss;
CREATE DATABASE IF NOT EXISTS hit_himss_account;
CREATE USER IF NOT EXISTS 'himss'@'%' IDENTIFIED BY 'db_password';
GRANT ALL PRIVILEGES ON hit_himss.* TO 'himss'@'%' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON hit_himss_account.* TO 'himss'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;