CREATE DATABASE IF NOT EXISTS hit_onc;
CREATE DATABASE IF NOT EXISTS hit_onc_account;
CREATE USER IF NOT EXISTS 'onc'@'%' IDENTIFIED BY 'db_password';
GRANT ALL PRIVILEGES ON hit_onc.* TO 'onc'@'%' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON hit_onc_account.* TO 'onc'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;